#@ load("@ytt:data", "data")
#@ load("@ytt:struct", "struct")
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.28.0

sources:
#@ images = struct.decode(data.values.eirini)
#@ for key in images["image_meta"]:
  #@ subcomponent = struct.encode(images["image_meta"][key])
  - imageRepo: #@ subcomponent.image_repository
    path: #@ subcomponent.source_path
    docker:
      build:
        file: #@ subcomponent.dockerfile
        buildkit: true
        rawOptions:
        - "--build-arg"
        - #@ "GIT_SHA=" + images["git_sha"]
#@ end
