#@ load("@ytt:data", "data")
#@ load("@ytt:struct", "struct")
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config

sources:
#@ images = struct.decode(data.values.eirini)
#@ for key in images:
#@ image = struct.encode(images[key])
- image: #@ image.image
  path: eirini/
  docker:
    build:
      file: #@ image.dockerfile
      buildkit: true
      rawOptions: ["--build-arg", "GIT_SHA=12345"]
#@ end