---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config

sources:
- image: cloudfoundry/eirini-opi-cf-for-k8s
  path: eirini/
  docker:
    build:
      file: docker/opi/Dockerfile
      buildkit: true
      rawOptions: ["--build-arg", "GIT_SHA=12345"]

searchRules:
- keyMatcher:
    path: [eirini, opi]