---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.11.0
directories:
- path: eirini
  contents:
  - path: .
    git:
      url: https://github.com/cloudfoundry-incubator/eirini.git
      ref: 2.0.0